### ISSUE TITLE
warning: demands usage of `hasTable` before `createTable`

### ISSUE THREAD

**Issue by zss007** [node-casbin/basic-adapter#18]
### Bug

`Knex:warning - Use async .hasTable to check if table exists and then use plain .createTable. Since .createTableIfNotExists actually just generates plain "CREATE TABLE IF NOT EXIST..." query it will not work correctly if there are any alter table queries generated for columns afterwards. To not break old migrations this function is left untouched for now, but it should not be used when writing new code and it is removed from documentation.`

just like this [https://github.com/knex/knex/issues/2489](url)

**Comment by zhmushan** [comment]
This is by design, not a bug.

I just used `Knex` to build the SQL string, but did not use it to initialize a connection, so I cannot use schema-related APIs

**Comment by luke88jones** [comment]
Is the point of this issue not that the code in the `createTable` function is not considered best practice by Knex anymore? Also, it seems like the schema API is being used in the function but it's not possible to pass a schema name to the Knex config. 

Should it be along these lines? 

```JS
  private async createTable(): Promise<void> {
    const tableExists = await this.knex.hasTable(CasbinRuleTable);

    if (tableExists) return;

    const createTableSQL = this.knex
      .createTable(CasbinRuleTable, (table) => {
        table.increments();
        table.string('ptype').notNullable();
        for (const i of ['v0', 'v1', 'v2', 'v3', 'v4', 'v5']) {
          table.string(i);
        }
      })
      .toQuery();

    await this.query(createTableSQL);
  }
```

**Comment by hsluoyz** [comment]
@luke88jones this issue was deprecated two years ago. If you want answers from Casbin team, please create a new issue

**Comment by luke88jones** [comment]
@hsluoyz Sure thing, I was just worried about creating a duplicate issue and having it closed

https://github.com/node-casbin/basic-adapter/issues/24
