### ISSUE TITLE
Fix the CI

### ISSUE THREAD

**Issue by hsluoyz** [node-casbin/basic-adapter#19]
See:

![image](https://user-images.githubusercontent.com/3787410/97109942-366e1900-1711-11eb-925c-d8db73f054aa.png)

**Comment by hsluoyz** [comment]
@zhmushan

**Comment by hsluoyz** [comment]
@nodece @stu01509

**Comment by hsluoyz** [comment]
@zhmushan any idea about why the CI badge shows failing?

**Comment by divy9881** [comment]
The last commit which was pushed on `master` branch had a CI failure. Hence, the badge shows the failing status.
