### ISSUE TITLE
fix: the push on master branch 

### ISSUE THREAD

**Issue by divy9881** [node-casbin/basic-adapter#22]
![image](https://user-images.githubusercontent.com/39230975/104087955-4d8cc380-5289-11eb-8bc9-89700e94e1e1.png)

**Comment by divy9881** [comment]
It requires atleast 1 review for pushing the commits. So, the action for semantic-release fails.

**Comment by hsluoyz** [comment]
@divy9881 but I have reviewed and approved, right? https://github.com/node-casbin/basic-adapter/pull/21 why is there still this error?

![image](https://user-images.githubusercontent.com/3787410/104088119-761fb800-529f-11eb-9254-051b4cd8cebc.png)

**Comment by divy9881** [comment]
Thats maybe due to lack in permissions given to the access-token which is being used in `env`. The admin of this org need to change the permissions.

https://github.com/node-casbin/basic-adapter/blob/f7734623859444dfed2c633f9ca8cb6f1c1919b3/.github/workflows/ci.yml#L87

**Comment by hsluoyz** [comment]
@divy9881 The docs (https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#about-the-github_token-secret) said `GITHUB_TOKEN` will be created automatically by GitHub. Why is it not there?

![image](https://user-images.githubusercontent.com/3787410/104088749-f1836880-52a3-11eb-9ffa-e18856a04020.png)
