### ISSUE TITLE
Update implementation to remove Knex warnings 

### ISSUE THREAD

**Issue by luke88jones** [node-casbin/basic-adapter#24]
When running an application with this library we receive the following message on startup

`Use async .hasTable to check if table exists and then use plain .createTable. Since .createTableIfNotExists actually just generates plain "CREATE TABLE IF NOT EXIST..." query it will not work correctly if there are any alter table queries generated for columns afterwards. To not break old migrations this function is left untouched for now, but it should not be used when writing new code and it is removed from documentation.`

Can the implementation of the `createTable` function be updated to accommodate the suggested changes?  I'm happy to submit a PR.

**Comment by hsluoyz** [comment]
@luke88jones hi, can you make a PR?
